[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#222433"
foreground = "#929be5"

[cursor]
thickness = 0.1

[cursor.style]
shape = "Beam"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors.normal]
black = "#282b39"
blue = "#589ec6"
cyan = "#59b6b6"
green = "#7cbe8c"
magenta = "#b871b8"
red = "#dc6f7a"
white = "#fdfdfd"
yellow = "#a8a384"

[scrolling]
history = 1000
multiplier = 5

[window]
dynamic_padding = true

[window.padding]
x = 15
y = 8

[terminal.shell]
program = "/bin/nu"
